[package]
name = "hmac"
version = "0.1.0"
edition = "2021"

[dependencies]
generic-array = "1.1.0"
numeric-array = "0.6.1"
rand = "0.8.5"
rayon = "1.10.0"
sha2 = "0.10.8"
sha1 = "0.10" 
hmac = "0.12.1"